name: Deploy Docusaurus to GCP Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEVELOPERS_SITE }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to GCP Storage Bucket
        run: |
          gsutil -m rsync -r build gs://developers.nestbox.ai

      - name: Set Website Bucket Permissions
        run: |
          gsutil iam ch allUsers:objectViewer gs://developers.nestbox.ai
